version: '2'
services:

  redis:
    image: "redis"
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"

{% if cookiecutter.participant_type == "arbiter" %}

  balancemanager_{{ cookiecutter.participant_name_slug }}:
    image: "polyswarm/polyswarm-client:latest"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - marketplace.env
    volumes:
      - "../keyfiles:/keyfiles:ro"
    command:
      - "balancemanager"
      - "maintain"
      - "1"
      - "10000001"
    

{% endif %}

{% if cookiecutter.participant_type == "microengine" or cookiecutter.participant_type == "ambassador" %}

  balancemanager_{{ cookiecutter.participant_name_slug }}:
    image: "polyswarm/polyswarm-client:latest"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - marketplace.env
    volumes:
      - "../keyfiles:/keyfiles:ro"
    command:
      - "balancemanager"
      - "maintain"
      - "10000"
      - "10000"

{% endif %}

{% if cookiecutter.participant_type == "microengine" or cookiecutter.participant_type == "arbiter" %}

  {{ cookiecutter.participant_type }}-frontend_{{ cookiecutter.participant_name_slug }}:
    image: "polyswarm/polyswarm-client:latest"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_ADDR=redis:6379
      - QUEUE={{ cookiecutter.project_slug }}
    depends_on:
      - redis
    env_file:
      - marketplace.env
    volumes:
      - "../keyfiles:/keyfiles:ro"
    command:
      - "dockerize"
      - "-wait"
      - "tcp://redis:6379"
      - "-timeout"
      - "1000s"
      - "{{ cookiecutter.participant_type }}"
      - "--log"
      - "INFO"
      - "--backend"
      - "producer"
      - "--chains"
      - "side"
      {% if cookiecutter.microengine_arbiter__supports_scanning_files == "true" %}- "--artifact-type"
      - "file"{% endif %}
      {% if cookiecutter.microengine_arbiter__supports_scanning_urls == "true" -%}- "--artifact-type"
      - "url"{%- endif -%}

{% if cookiecutter.platform == "linux" %}

  {{ cookiecutter.participant_type }}-worker_{{ cookiecutter.participant_name_slug }}:
    image: "{{ cookiecutter.project_slug }}"
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_ADDR=redis:6379
      - QUEUE={{ cookiecutter.project_slug }}
    depends_on:
      - redis
    env_file:
      - marketplace.env
    command:
      - "dockerize"
      - "-wait"
      - "tcp://redis:6379"
      - "-timeout"
      - "1000s"
      - "worker"
      - "--log"
      - "INFO"
      - "--backend"
      - "{{ cookiecutter.package_slug }}"

{% endif %}

{% endif -%}

{% if cookiecutter.participant_type == "ambassador" %}

  {{ cookiecutter.participant_type }}-{{ cookiecutter.participant_name_slug }}:
    image: "{{ cookiecutter.project_slug }}"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - marketplace.env
    volumes:
      - "../keyfiles:/keyfiles:ro"
    command:
      - "{{ cookiecutter.participant_type }}"
      - "--log"
      - "INFO"
      - "--chains"
      - "side"
      - "--backend"
      - "{{ cookiecutter.package_slug }}"
    

{% endif %}
