version: '3.4'
services:
  
  test_{{ cookiecutter.participant_name_slug }}:
    image: "{{ cookiecutter.project_slug }}"
    environment:
      - PYTHONUNBUFFERED=1
    command: ["pytest", "-s", '--log-cli-level=INFO']
